### ISSUE TITLE
longtype not supported as column name

### ISSUE THREAD

**Issue by target33** [sebgiroux/Cassandra-Cluster-Admin#1]
when column name is longtype greater than 32 bit (for example 10999888777) only the 32 bit part is displayed (2409954185)

**Comment by sebgiroux** [comment]
Thank you for the bug report!

Looks like this is a bug in PHPcassa with number greater then 32 bits integer as you said. I will check with thobbs what we can do about that! :)

**Comment by sebgiroux** [comment]
Sorry, closed it by accident. I posted a possible fix in your PHPcassa issue. Let's see if thobbs like it :)

**Comment by target33** [comment]
That's perfect, works great! Thanks
