### ISSUE TITLE
[Feature Request] Handle multiline fields

### ISSUE THREAD

**Issue by mNantern** [sebgiroux/Cassandra-Cluster-Admin#10]
It would be nice to handle multiline fields (XML for example).

Because I just try with some XML and all I got is a blank page (probably because of the type "input" instead of textarea).

Thank you in advance

**Comment by sebgiroux** [comment]
I will take a look, are you talking about any page in particular ? "Browse Data" maybe  ?

Thank you!

**Comment by sebgiroux** [comment]
I think i've just added what you need, multi-line value inserting/editing and properly display of xml. Please pull the latest version and let me know if we can close this issue! :)

**Comment by mNantern** [comment]
Yes, it's exactly that kind of modification I was talking about.

Nice work, everything works well.

Thank you !
