### ISSUE TITLE
Access problems

### ISSUE THREAD

**Issue by gang0713** [sebgiroux/Cassandra-Cluster-Admin#15]
cassandra Increase access, visit has been wrong

error:An error occured while connecting to your Cassandra server: You have not logged in

But I landing was successful, but can't access the data.
my access.properties
system Under the table Access is all
 ro

**Comment by sebgiroux** [comment]
I'm not too sure if I understand what you're saying ?! Any chance that you tried with PHPcassa itself, does it work ? Are you saying you are using a username/password on your Cassandra cluster ? Did you specify the credentials in the CASSANDRA_CLUSTERS array ?

**Comment by gang0713** [comment]
my conf.inc.php
$CASSANDRA_CLUSTERS = array(array('nodes' => array('192.168.193.104:9160'),
                                                                     'username' => 'pimda',
                                                                     'password' => 'pimda'));

```
    /*
            Read-only keyspace

            Some keyspace can be set to read-only so nothing can be added/edited/deleted from them.
    */

    define('READ_ONLY_KEYSPACES','system'); // Seperate by comma (,)

    /*
            Enter your Cassandra Cluster Admin credentials here
    */
    define('CCA_LOGIN_REQUIRED',true);
    define('CCA_USERNAME','pimda');
    define('CCA_PASSWORD','pimda');
    define('MX4J_HTTP_ADAPTOR_PORT',8081);
```

but through the browser visit times wrong:
error:An error occured while connecting to your Cassandra server: You have not logged in

Through the opscenter can normal visit.

**Comment by sebgiroux** [comment]
Which version of Cassandra are you using ? I'm trying to test with 1.0 but it looks like authentication was removed because it wasn't production ready. I think your best bet is probably to find another way to protect your node from getting accessed from the outside (ex: only give access to internal connection for that port). Without username and password, CCA should work fine.

**Comment by gang0713** [comment]
version :apache-cassandra-1.1.0
Without username and password, CCA is work fine.But I want to have the access control.

I already increased for the access control,I get on from SVN SimpleAuthority
and SimpleAuthenticator.

https://github.com/apache/cassandra/tree/trunk/examples/simple_authentication/src/org/apache/cassandra/auth

 through the Cassandra-cli and opscenter visit is ok.

**Comment by sebgiroux** [comment]
Did you compile your own Cassandra with those class (If that's the case, can you send me the jar file) ? I'm not sure what I'm supposed to do with those file :/

**Comment by gang0713** [comment]
------------------ 原始邮件 ------------------
发件人: "Sébastien Giroux"reply@reply.github.com;
发送时间: 2012年5月29日(星期二) 上午9:50
收件人: "ss"4973357@qq.com; 

主题: Re: [Cassandra-Cluster-Admin] Access problems (#15)

Did you compile your own Cassandra with those class (If that's the case, can you send me the jar file) ? I'm not sure what I'm supposed to do with those file :/

---

**Comment by gang0713** [comment]
I send mail to  "Sébastien Giroux"<reply+i-4729490-a6ba3d326928f979e9426b5ce0f336e3e0af0fc6-1773414@reply.github.com>;

Can you receive it

**Comment by sebgiroux** [comment]
Nope. please try: emailremoved

Thank you!

**Comment by gang0713** [comment]
Has been sent to you.Please find.

**Comment by sebgiroux** [comment]
Just fixed an issue. credentials were passed as the wrong parameter. Can you git pull and test again please ?

Thank you!

**Comment by gang0713** [comment]
Well, thanks1
