### ISSUE TITLE
Missing columns from row?

### ISSUE THREAD

**Issue by scott-mackenzie** [sebgiroux/Cassandra-Cluster-Admin#16]
Any idea why every row with more than 100 columns is being truncated to100 when viewing with CCA?  As an example within cassandra-cli the count is 157 and in within CCA only 100 show?

/s

**Comment by sebgiroux** [comment]
Should be fixed now, default column count is 10k and you can increase it as needed. I think the new PHPcassa should fix that issue but it should be good enough for now. Let me know if you have any more issue.

Thank you!
