### ISSUE TITLE
there's something wrong with the method "change keyspace name"

### ISSUE THREAD

**Issue by gzkiko** [sebgiroux/Cassandra-Cluster-Admin#2]
when I changed the keyspace 's name from 'keyspace1' to 'myspace', it output the message like below:

Fatal error: Uncaught exception 'cassandra_NotFoundException' in E:\WampServ\www\phpcassa\thrift\Thrift.php:574 Stack trace: #0 E:\WampServ\www\phpcassa\thrift\packages\cassandra\Cassandra.php(3769): TBase->_read('Cassandra_descr...', Array, Object(TBinaryProtocolAccelerated)) #1 E:\WampServ\www\phpcassa\thrift\packages\cassandra\Cassandra.php(1357): cassandra_Cassandra_describe_keyspace_result->read(Object(TBinaryProtocolAccelerated)) #2 E:\WampServ\www\phpcassa\thrift\packages\cassandra\Cassandra.php(1318): CassandraClient->recv_describe_keyspace() #3 E:\WampServ\www\phpcassa\sysmanager.php(506): CassandraClient->describe_keyspace('Keyspace12') #4 E:\WampServ\apps\Cassandra-Cluster-Admin\keyspace_action.php(206): SystemManager->describe_keyspace('Keyspace12') #5 {main} thrown in E:\WampServ\www\phpcassa\thrift\Thrift.php on line 574

**Comment by sebgiroux** [comment]
You're right, I have commited a "fix" so it doesnt error out, but the problem is that phpcassa doesn't support renaming keyspace/column family just yet. I will ask thobbs if it would be possible to support this so I will leave this issue open for now in hope of supporting that feature soon :)

Thanks for the report!

**Comment by sebgiroux** [comment]
thobbs confirmed Cassandra doesn't support renaming keyspace or column family yet, so unfortunatly nothing else I can do for now, sorry!

**Comment by gzkiko** [comment]
thanks for your reply, i got it

kiko Zhang
 2011-9-14 11:25"Sbastien Giroux" <
reply@reply.github.com
