### ISSUE TITLE
why I can't get value from CLI which insert by CCA?

### ISSUE THREAD

**Issue by gzkiko** [sebgiroux/Cassandra-Cluster-Admin#3]
I inserted some value into a CF by CCA, and I can browse and get it by CCA, and, it can read by php that i programed , but it can 't read under cassandra-cli, how was it?

**Comment by sebgiroux** [comment]
If you can read it from PHP, that mean that the cli command you're using is probably wrong. Unfortunatly, this is not a CCA issue, so I will close this for now and you should be able to get some help about this on the mailing list.

Thank you!
