### ISSUE TITLE
JMX ERROR 500

### ISSUE THREAD

**Issue by arodrime** [sebgiroux/Cassandra-Cluster-Admin#4]
Hi,

I'm using your solution in my small start-up, it's a nice free alternative to the very expensive Datastax Opscenter, thanks for it.

But to really replace it I need statistics. It seems that jmx stats can give me that but I wasn't able to see them.

I got an internal error when trying to get jmx.php page.

I got a 2 nodes cluster that I configured in the include/conf.inc.php. I'm sur that my mx4j is successfully loaded on each node on cassandra start :

"INFO 08:43:47,742 mx4j successfuly loaded
HttpAdaptor version 3.0.2 started on port 8081"

Did you already heard about this kind of error ?

Should you need any further information, please do not hesitate to let me know.

**Comment by sebgiroux** [comment]
Hi,

Do you have access to the web server error log ? It sounds like there should be a PHP error in there. If you could find it, it would really help me figure this problem out.

There is not much stuff on the stats page yet so hopefully you won't be dissapointed once it finally show up :) I'm always welcome to suggestionon what to add to it tho

Thank you!

**Comment by arodrime** [comment]
Oops I should have looked to the apache log, sorry of having bother you.

I just hadn't curl installed and you use it on "helper/MX4J.php".

I close this issue.

**Comment by sebgiroux** [comment]
Yep, not having CURL installed will cause problem for sure. Actually, I will handle that case properly and display an error message when CURL is not installed instead of miserably crashing :)
