### ISSUE TITLE
Wrong mx4j_node when selecting a new node from dropdown menu

### ISSUE THREAD

**Issue by mvsantos** [sebgiroux/Cassandra-Cluster-Admin#5]
Line 16 of jmx.php currently is set as below
if (isset($_GET['change_mx4j_node'])) $_SESSION['mx4j_node'] = $_GET['mx4j_node'];

But observing the logic below line 16, the correct _GET paramenter setting _SESSION[mx4j_node] should be change_mx4j_node instead of mx4j_node
Making that line  
if (isset($_GET['change_mx4j_node'])) $_SESSION['mx4j_node'] = $_GET['change_mx4j_node'];

**Comment by sebgiroux** [comment]
Good catch!

I just commited your fix, thanks a lot!
