### ISSUE TITLE
exception while inserting row 

### ISSUE THREAD

**Issue by seremenko** [sebgiroux/Cassandra-Cluster-Admin#6]
Hello.

I've got exception while i am trying to insert row

Error while inserting row: An attempt to execute batch_mutate failed 6 times. The last error was exception 'cassandra_UnavailableException' in /home/sergey/workspace/test/cassandra/test/include/phpcassa/thrift/packages/cassandra/Cassandra.php:871 Stack trace: #0 /home/sergey/workspace/test/cassandra/test/include/phpcassa/thrift/packages/cassandra/Cassandra.php(871): thrift_protocol_read_binary(Object(TBinaryProtocolAccelerated), 'cassandra_Cassa...', false) #1 /home/sergey/workspace/test/cassandra/test/include/phpcassa/thrift/packages/cassandra/Cassandra.php(846): CassandraClient->recv_batch_mutate() #2 [internal function]: CassandraClient->batch_mutate(Array, 1) #3 /home/sergey/workspace/test/cassandra/test/include/phpcassa/connection.php(354): call_user_func_array(Array, Array) #4 /home/sergey/workspace/test/cassandra/test/include/phpcassa/columnfamily.php(617): ConnectionPool->call('batch_mutate', Array, 1) #5 /home/sergey/workspace/test/cassandra/test/columnfamily_action.php(512): ColumnFamily->insert('test', Array) #6 {main}

Is that my mistake or your lib bug ?

**Comment by sebgiroux** [comment]
1. Did you pull the latest version from the repository ? If not, try the latest
2. I will need more info about which version of cassandra you're using, does this happen all the time or only once in a while, etc. ?

Thank you!

**Comment by castiel** [comment]
cassandra_UnavailableException ->     Not all the replicas required could be created and/or read. 

read here: http://wiki.apache.org/cassandra/API

You have probably choosen Network topology on your Strategy, which requires at least one Replica, which you probably don't have, but have only one server?

**Comment by sebgiroux** [comment]
Yeah try simple topology strategy instead :)
