### ISSUE TITLE
Error adding anything to a keyspace

### ISSUE THREAD

**Issue by ekaleido** [sebgiroux/Cassandra-Cluster-Admin#7]
Error while inserting row: An attempt to execute batch_mutate failed 6 times. The last error was exception 'cassandra_UnavailableException' in /var/www/cluster-admin/include/phpcassa/thrift/Thrift.php:574 Stack trace: #0 /var/www/cluster-admin/include/phpcassa/thrift/packages/cassandra/Cassandra.php(3181): TBase->_read('Cassandra_batch...', Array, Object(TBinaryProtocolAccelerated)) #1 /var/www/cluster-admin/include/phpcassa/thrift/packages/cassandra/Cassandra.php(886): cassandra_Cassandra_batch_mutate_result->read(Object(TBinaryProtocolAccelerated)) #2 /var/www/cluster-admin/include/phpcassa/thrift/packages/cassandra/Cassandra.php(846): CassandraClient->recv_batch_mutate() #3 [internal function]: CassandraClient->batch_mutate(Array, 1) #4 /var/www/cluster-admin/include/phpcassa/connection.php(354): call_user_func_array(Array, Array) #5 /var/www/cluster-admin/include/phpcassa/columnfamily.php(617): ConnectionPool->call('batch_mutate', Array, 1) #6 /var/www/cluster-admin/columnfamily_action.php(512): ColumnFamily->insert('test', Array) #7 {main}

**Comment by sebgiroux** [comment]
Try to create your keyspace with simple topology strategy instead of network topology strategy and see if that help :)

**Comment by quentar** [comment]
and/or set replication factor of keyspace correctly , beware having it zero or greater than one if you are running just a local node (then you should probably set replication factor to 1 )
